# get source archive if not present
function(get_source_archive url ar_name)
	set(full_ar_name "${CMAKE_CURRENT_LIST_DIR}/${ar_name}")
	if (NOT EXISTS ${ar_name})
		MESSAGE("Downloading from '${url}'.")
		FILE(DOWNLOAD ${url} ${full_ar_name} SHOW_PROGRESS)
	else()
		MESSAGE("Found '${ar_name}'.")
	endif()
endfunction(get_source_archive)

function(unpack_source srcdir)
	if (NOT EXISTS ${srcdir})
		FILE(GLOB ark RELATIVE ${CMAKE_CURRENT_LIST_DIR} "${srcdir}.tar.*")
		STRING(LENGTH ${srcdir} srcdirlen)
		STRING(SUBSTRING ${ark} ${srcdirlen} -1 arkext)
		if (${arkext} STREQUAL ".tar.xz")
			SET(tar_flags "xJf")
		elseif(${arkext} STREQUAL ".tar.gz")
			set(tar_flags "xzf")
		endif()
		MESSAGE("Unpacking source: 'tar ${tar_flags} ${ark}'.")
		EXECUTE_PROCESS(COMMAND "tar" ${tar_flags} ${ark}
			WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
	else()
		MESSAGE("Found '${srcdir}'.")
	endif()
endfunction(unpack_source)
